### ISSUE TITLE
Write authoring documentation

### ISSUE THREAD

**Issue by Kacarott** [codewars/lambda-calculus#25]
To be added to CW docs.

- [x] How to use module
- [x] How to write tests with it
- [x] Style guide

**Comment by JohanWiltink** [comment]
I'm starting to much like kebab-case as a naming convention. No `Shift` key _necessary_ anywhere, complete freedom in initial capitalisation, doesn't interfere with anything that I can think of. Could recommend not _ending_ a name in `-`, but absolutely no need to enforce this. This would work well for me as a standard library style.
ETA: camelCase has the advantage in making imports into tests easier though - less renaming required ( but it can be done ).

I have much fewer and less developed ideas on indentation and parenthesisation.

Style Guide could _suggest_ `n-1` as an argument name for use with Scott Numerals.

Lots of things can actually be ad-hoc though, and our syntax ( by design ) _allows_ for many different conventions in naming, indentation and line continuation. "Be consistent" would be my most important advice.

For something like a Church `succ`, I'd like to _recommend_ `succ = \ n . \ f x . f (n f x)` to show the conceptual difference between `succ` arguments and `num` constructor arguments.

**Comment by JohanWiltink** [comment]
Having the Style guide recommend certain, limited, assigned names might help preventing ( some ) clashes.

All single and some double capitals reserved for standard combinators ( as documented [here](https://www.angelfire.com/tx4/cus/combinator/birds.html), plus `BB, CB, KK, CK, KI` as defined in `combinators.lc` ). `OR` should probably be allowed as `||`.

I'd like `zero, succ, pred, add, sub, mul, div, mod, pow, gcd, lcm, LT, EQ, GT, compare, lt, le, eq, ge, gt, True, False, not, and, or, xor, Pair, fst, snd` to not have surprising implementations. Specifically `plus, times` might be usefully repurposed for other operations - they don't need to work on numbers only.
Constructors ( except for numbers, and possibly lists ) preferably capitalised, mainly to prevent clashes with JS `true, false`. I irrationally prefer `cons, nil, zero, one` &c uncapitalised.

Using Haskell standard list manipulation function names ( `head, tail, ..` plus adaptations like `append` for `++` ) are probably also not the best idea to alternatively define. ( It's a shame `null` can never be exported. See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords) for a comprehensive list of reserved words and literals. Note that, amongst others, `undefined, module,require` _can_ be overwritten - but that doesn't necessarily make it a good idea to do so. )

**Comment by JohanWiltink** [comment]
For the Style Guide: spaces, not tabs. or your parse error message pointers will be misaligned.

I don't really care how many spaces anyone uses for an indent level. Two doesn't really create a visual indent under `\ ` or `( `; four is often wasteful of screen real estate.

**Comment by JohanWiltink** [comment]
Maybe for the Style Guide, maybe for the formal syntax specs: comments should have whitespace following the `#`.

`#` immediately followed by non-whitespace is reserved for future expansion ( ie, compiler directives ).

**Comment by JohanWiltink** [comment]
Probably recommend setting `verbosity Concise` for `Submit` tests. Solvers can't change that; `Calm` is _very_ sparse.

**Comment by JohanWiltink** [comment]
How to use module -> Verbosity levels:

Setting verbosity to `Verbose` shows references in use from the environment while compiling. This evaluates those references, which normally might never happen if a definition is never used. So this might (!) also create `eval` errors that would _not_ happen without debugging.

I think it's a small price to pay, but it's something to document.

**Comment by JohanWiltink** [comment]
Maybe we _should_ have a document defining the syntax.

Not everyone may have "the usual syntax" internalised and we have some restrictions on that as well.

**Comment by Kacarott** [comment]
Yes I think an "introductory" document which defines syntax and gives a very brief introduction to LC (with links to wiki/etc) would be good. Then some beginner katas, and some of the existing multilingual LC katas can provide a link to the document in the initial solution.

**Comment by JohanWiltink** [comment]
For the Testing Guide: recommend ending any code in `preloaded.lc` with a dummy definition like `_ = ()` to prevent cheating by starting `solution.lc` as a line continuation.

Code has to be compiled as a single block of text if user solutions are to be able to access `Preloaded` definitions, so preventing `solution.lc` from starting with a continuation is not possible - nothing you can put in `preloaded.lc` will uncontinue the last definition without causing a syntax error.

Note that `Preloaded` can be compiled separately if only the test suite needs access to definitions in it - but this offers no advantage over simply defining them in JS.
